version: '3'

services:
  proxy:
    image: nginx:alpine
    container_name: twitfix_proxy
    volumes:
      - ./twitfix_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
    depends_on:
      - twitfix

  twitfix:
    build: .
    image: kvdomingo/twitfix
    volumes:
      - ./twitfix/config.json:/twitfix/config.json:ro
